# Generated by Django 5.0 on 2024-03-24 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator]),
        ),
    ]
