# Generated by Django 5.0 on 2024-02-23 17:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisements', '0017_remove_advertisements_created_at_str'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, validators=[django.core.validators.MinLengthValidator(limit_value=1)])),
                ('created_ad', models.DateTimeField(auto_now_add=True, verbose_name='Chat message creation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.advertisements')),
                ('companions', models.ManyToManyField(to=settings.AUTH_USER_MODEL, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Minimum 2 companion'), django.core.validators.MaxLengthValidator(limit_value=2, message='Maximum 2 companion')])),
                ('messages', models.ManyToManyField(blank=True, to='chat.message')),
            ],
        ),
    ]
