# Generated by Django 5.0 on 2024-02-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_companions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
