# Generated by Django 5.0 on 2024-02-23 21:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_created_ad_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, null=True, size=None),
        ),
    ]
