# Generated by Django 5.0 on 2024-02-24 11:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=500), blank=True, null=True, size=None),
        ),
    ]
