# Generated by Django 5.0 on 2024-01-22 18:02

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(limit_value=50, message='Minimum number of characters: 50')], verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Price')),
                ('barter', models.TextField(default='', max_length=1000, validators=[django.core.validators.MinLengthValidator(limit_value=50, message='Minimum number of characters: 50')])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creation')),
                ('location', models.TextField(max_length=1000, verbose_name='Location')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(limit_value=1, message='There must be at least one image')]), blank=True, size=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
