# Generated by Django 5.0 on 2024-01-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='condition',
            field=models.CharField(null=True),
        ),
    ]
