# Generated by Django 5.0 on 2024-01-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisements_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisements',
            name='barter',
        ),
    ]
