# Generated by Django 5.0 on 2024-01-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_alter_advertisements_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='subcategory',
            field=models.CharField(default='', max_length=100, verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='category',
            field=models.CharField(default='', max_length=100, verbose_name='Category'),
        ),
    ]
