# Generated by Django 5.0 on 2024-01-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_advertisements_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='location',
            field=models.TextField(default='', max_length=1000, verbose_name='Location'),
        ),
    ]
