# Generated by Django 5.0 on 2024-01-25 19:43

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_alter_advertisements_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, size=None, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='There must be at least three image')]),
        ),
    ]
