# Generated by Django 5.0 on 2024-01-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0009_alter_advertisements_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='condition',
            field=models.CharField(choices=[('b/w', 'Б/у'), ('new', 'Новый')], default='b/w'),
        ),
    ]
