# Generated by Django 5.0 on 2024-01-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0010_alter_advertisements_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
