# Generated by Django 5.0 on 2024-01-30 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0011_alter_advertisements_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='description',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(limit_value=50, message='Minimum number of characters: 50')], verbose_name='description'),
        ),
    ]
