# Generated by Django 5.0 on 2024-01-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0014_alter_advertisements_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='category',
            field=models.CharField(choices=[('personal_effects', 'Личные вещи'), ('electronics', 'Электроника'), ('hobbies_and_recreation', 'Хобби и отдых'), ('for_home_and_cottage', 'Для дома и дачи')], max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='subcategory',
            field=models.CharField(choices=[('clothes_shoes_accessories', 'Одежда, обувь, аксессуары'), ('watches_and_jewelry', 'Часы и украшения'), ('beauty_and_health', 'Красота и здоровье'), ('household_appliances', 'Бытовая техника'), ('furniture_and_interior', 'Мебель и интерьер'), ('cookware_and_kitchenware', 'Посуда и товары для кухни'), ('foodstuffs', 'Продукты питания'), ('audio_and_video', 'Аудио и видео'), ('games_consoles_programs', 'Игры, приставки и программы'), ('PC', 'ПК'), ('laptops', 'Ноутбуки'), ('tablets_and_e-books', 'Планшеты и электронные книги'), ('Phones', 'Телефоны'), ('PC_Products', 'Товары для ПК'), ('photographic_equipment', 'Фототехника'), ('bicycles', 'Велосипеды'), ('books_and_magazines', 'Книги и журналы'), ('collecting', 'Коллекционирование'), ('musical_instruments', 'Музыкальные инструменты'), ('sports_and_recreation', 'Спорт и отдых')], max_length=100, verbose_name='Subcategory'),
        ),
    ]
