# Generated by Django 5.0 on 2024-02-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0015_alter_advertisements_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='created_at_str',
            field=models.CharField(default=''),
        ),
    ]
