# Generated by Django 5.0 on 2024-02-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0016_advertisements_created_at_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisements',
            name='created_at_str',
        ),
    ]
