# Generated by Django 5.0 on 2024-01-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar_url',
            new_name='avatar',
        ),
    ]
