# Generated by Django 5.0 on 2024-01-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(default='https://707.su/LpC'),
        ),
    ]
