# Generated by Django 5.0 on 2024-01-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
