# Generated by Django 5.0 on 2024-01-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_remove_user_slug'),
        ('advertisements', '0007_alter_advertisements_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advertisements',
            field=models.ManyToManyField(blank=True, related_name='Advertisements', to='advertisements.advertisements'),
        ),
    ]
