# Generated by Django 5.0 on 2024-02-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_user_advertisements'),
        ('advertisements', '0015_alter_advertisements_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='Favorites', to='advertisements.advertisements'),
        ),
    ]
