# Generated by Django 5.0 on 2024-02-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_user_subscribers_alter_user_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribers',
        ),
    ]
